### ISSUE TITLE
Commit V3

### ISSUE THREAD

**Issue by dvdrtrgn** [gatsbyjs/tutorial-example#1]
Seems like https://www.gatsbyjs.com/docs/tutorial/ should be in here

**Comment by meganesu** [comment]
Hi! Thanks for opening an issue. The Tutorial is linked in the repo description (shown in the screenshot below in the sidebar on the right).

I'm going to close this PR, but feel free to reopen and add additional details if there was something else you wanted to add! 💜 


<img width="1293" alt="Screenshot of the gatsbyjs/tutorial-example repo, with the link to the Tutorial on the Gatsby docs site highlighted" src="https://user-images.githubusercontent.com/3609989/138394528-851d206f-716e-4806-81ef-68cdd7352d30.png">
