### ISSUE TITLE
StaticImage gives unhandled runtime error (Step 3 - Plugins)

### ISSUE THREAD

**Issue by jbryan83** [gatsbyjs/tutorial-example#4]
I have followed the tutorial steps to a "T" but am getting stuck on step 3. As soon as I add <StaticImage> to the code and reload the server, I get an unhandled runtime error with the following details:

undefined is not an object (evaluating 'originalFactory.call')
:
No codeFrame could be generated

**Comment by yorkshiremoose** [comment]
If this is still a problem for you, I was running node 14.16 and I had the same issue, but when I upgraded node to 14.17.6, it worked fine. Hope that helps.

**Comment by LekoArts** [comment]
For questions about the tutorial, please use https://github.com/gatsbyjs/gatsby/discussions
